#!/bin/sh

# 监听LAN启动事件，强制拉回无线网卡
if [ "$ACTION" = "ifup" ] && [ "$INTERFACE" = "lan" ]; then
    sleep 2
    # 启用无线接口
    ip link set ra0 up
    ip link set rai0 up
    # 强制加入网桥
    ip link set ra0 master br-lan 2>/dev/null
    ip link set rai0 master br-lan 2>/dev/null
fi
